name: backend [py3.6]
on:
  push:
    branches:
      - master
      - releases/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-16.04
    timeout-minutes: 30
    strategy:
      matrix:
        instance: [0, 1, 2]

    env:
      MIGRATIONS_TEST_MIGRATE: 1

    steps:
      - uses: actions/checkout@v2

      - name: Check for python file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Set python version output
        id: python-version
        run: |
          echo "::set-output name=python-version::$(awk 'FNR == 2' .python-version)"

      # Until GH composite actions can use `uses`, we need to setup python here
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.python-version.outputs.python-version }}

      - name: Setup pip
        uses: ./.github/actions/setup-pip
        if: steps.changes.outputs.backend == 'true'
        id: pip

      - name: pip cache
        uses: actions/cache@v2
        if: steps.changes.outputs.backend == 'true'
        with:
          path: ${{ steps.pip.outputs.pip-cache-dir }}
          key: ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}-${{ hashFiles('**/requirements-*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}

      - name: Setup sentry env
        uses: ./.github/actions/setup-sentry
        if: steps.changes.outputs.backend == 'true'
        id: setup
        with:
          python: 3

      - name: Run backend test [py3.6] (${{ steps.setup.outputs.matrix-instance-number }} of ${{ strategy.job-total }})
        if: steps.changes.outputs.backend == 'true'
        run: |
          make travis-test-postgres
